### ISSUE TITLE
Whats your plan with this?

### ISSUE THREAD

**Issue by philkunz** [fvilers/qobuz#1]
Hi,

this is Phil from Lossless (https://lossless.com)
We planned on building a lossless streaming service ourselves back in 2014, but pivoted to Open Source SaaS products and consulting. 

We still have some cool bitperfect Player Tech left over that we recently updated to the state of the art and plan to release under MIT. We are currently looking into which music services to integrate and found this repo :)

Hence the question, what your plans are with this, and how much of the API you plan on implementing.

**Comment by fvilers** [comment]
Hi Phil,

Thanks for your message. At this first, I wrote this library in JavaScript (back in 2017) as I was building a web player to replace Qobuz one. Some time later, they released their new React based player that was OK to me so I stopped working on that.

This last summer I started rewriting it in TypeScript to finally have 100 % coverage of their API, to have a modernish version of the code, and for fun but I didn't had/took the time to finish. I tried to restart a few days ago just to find out that Quobuz policies have changed and they completely remove their API documentation from Github.

My goal is to finish this library, but I'll we be a bit harder just be reverse engineering. And moreover, I'm quite interested about your integration :-) I could take a few hours/days to finis this if you can convince me.
